<?php


namespace app\facade;


use think\Facade;

class Test extends Facade
{
//    getFacadeClass()绑定。
//    protected static function getFacadeClass()
//    {
////        parent::getFacadeClass(); // TODO: Change the autogenerated stub
//        return 'app\common\Test';
//    }
}